### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by TheHenker** [Dexon95/bustasatoshi#1]
This Gambling Site script does not work!

You can bet but the multipler does not increase!

0,00x

I think you need to integrate the APP Secret

**Comment by Dexon95** [comment]
the commit 645b8a478243da3c7a83b0c1fa13a81653985e34 and f1923ecea6370164ab3cce7cb02eb886c4727f8a should have fixed it i think.

**Comment by TheHenker** [comment]
Thanks
